name: Release

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release-please:
    name: Create release PR
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write # create releases and tags
      pull-requests: write # create and update release PRs
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
