name: Release

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89f3d4c557c4bd5bda612 # v4.2.0
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
